### PR TITLE
Fix /usr/etc/ in sota-client.service

### PR DESCRIPTION
**Pull request by jerrytrieu**

### CODE REVIEW

**Comment by taheris** [comment]
The `Makefile` and `CONFIG_PATH` in `sota_start.sh` still point to the old path.

**Comment by jerrytrieu** [comment]
@rdanitz why wasn't it changed to `/usr/etc` everywhere?

**Comment by rdanitz** [comment]
we didn't need to change the client at all at that time, see #246

**Comment by jerrytrieu** [comment]
@rdanitz the e2e is setting CONFIG_DIR?

**Comment by jerrytrieu** [comment]
But the systemd service file is not reading CONFIG_DIR.

**Comment by jerrytrieu** [comment]
See #261

**Comment by rdanitz** [comment]
in e2e we fetch the toml from `buildsrv` so indeed I think the change to sota-client was missing

**Pull request closed without merging**
