### PR TITLE
Pin trusted uptane root.json key-ids

### PR DESCRIPTION
**Pull request by taheris**
Resolves [ATS-02-001](https://github.com/advancedtelematic/cure53/issues/17).

### CODE REVIEW

**Comment by heartsucker** [comment]
You need to split the trusted root keys into two `HashSet`s because you're not allowed to mix roots of trust in a multirepo set up according to the spec. This  current implementation would allow someone to replace all the offline repo keys with compromised director keys and remove a huge amount of security benefits.

**Comment by taheris** [comment]
@heartsucker: the verifier has now been split by service

**Comment by taheris** [comment]
After speaking to Phil, we've decided this way will be too painful to use correctly (e.g. copy some key-ids from a website and paste it into `local.conf` before building a yocto image that writes these somewhere on the filesystem, then work out a rotation strategy to update them).

I'll open another PR where we trust that the initial `root.json` has been provisioned and trusted correctly, and ensures that each subsequent `root.json` is signed with the prior's keys.

**Comment by heartsucker** [comment]
@taheris Word. Let's talk tomorrow when I'm in the office.

**Pull request closed without merging**
