### PR TITLE
Add documentation to public functions

### PR DESCRIPTION
**Pull request by taheris**
[PRO-871](https://advancedtelematic.atlassian.net/browse/PRO-871).

There are a few additional stylistic changes for consistency. For example, renaming `secret` to `client_secret` and `Dpkg` to `Deb` which has been moved to a separate commit.

### CODE REVIEW

**Comment by stevana** [comment]
Cc:ing in @tkfu given that most of this is docs.

Any way we can make it part of CI that the make doc output gets published somewhere and linked to from the readme?

**Comment by taheris** [comment]
Yes, I've added the `make doc` target for that purpose, although we'd need to add some publishing step to have it hosted somewhere.

**Comment by tkfu** [comment]
I agree we should add a job to CI that pushes the generated docs. They currently live at http://advancedtelematic.github.io/rvi_sota_server/gen_docs/client/sota/, and advancedtelematic.github.io/rvi_sota_server is just the contents of the gh-pages branch of rvi_sota_server. So you ought to be able to update them from CI with a shell script like this:
```
make doc
git clone -b gh-pages git@github.com:advancedtelematic/rvi_sota_server.git
cd rvi_sota_server
rm -rf gen_docs/client/*
mv ../target/doc/* gen_docs/client/*
git add gen_docs/client
git commit
git push origin gh-pages
```

**Comment by tkfu** [comment]
Review Score: 11/11

**Pull request merged**
