### PR TITLE
Check for in-flight updates

### PR DESCRIPTION
**Pull request by taheris**
Resolves [PRO-1331](https://advancedtelematic.atlassian.net/browse/PRO-1331)

### CODE REVIEW

**Comment by taheris** [comment]
@stevana: the tests are failing but it's not immediately obvious why. From the client logs they don't seem to receive any commands. Maybe you can take a look and understand why.

**Comment by stevana** [comment]
This is the new update reordering test that fails, maybe @rdanitz has a clue?

**Comment by stevana** [comment]
Looks good otherwise.

**Comment by taheris** [comment]
The `queued` endpoint didn't work quite as I was expecting, so I've opened [PRO-1352](https://advancedtelematic.atlassian.net/browse/PRO-1352).

I've removed the looping call to `GetInFlightUpdates` for now until that is implemented, but I'll go ahead with this PR as the foundation is there and it has some additional small fixes. It will be simple to add the call again when 1352 is done.

**Pull request merged**
